name: test_feat
description: Test Feat Feature
publish_to: none
version: 0.0.1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.7.7"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flow_builder: ^0.0.9
  freezed_annotation: ^2.2.0
  get_it: ^8.0.3
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true
