name: {{name.snakeCase()}}
description: {{name.titleCase()}} feature package generated via the feature brick.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  i69n: ^3.0.0
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  freezed: ^2.5.7
  injectable_generator: ^2.6.2

